# -*- coding: utf-8 -*-
"""MA-231021004-TUGAS4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ijqiVoGYaKiUqOW9N7ho8S9QllUaSoe_
"""

import numpy as np

A = np.array([[2, 6, 2, 8],
              [9, 4, 5, 1],
              [2, 5, 9, 3],
              [11, 2, 8, 7]])

B = np.array([[3, 12, 5, 7],
              [2, 8, 9, 4],
              [1, 6, 3, 7],
              [9, 3, 2, 6]])

C = np.array([[6, 8, 2, 5],
              [1, 4, 9, 3],
              [7, 3, 1, 5],
              [9, 2, 4, 10]])
#TRANsPOSE MATRIKS A, B, C
print('TRANsPOSE MATRIKS')
At = np.transpose(A)
Bt = np.transpose(B)
Ct = np.transpose(C)
print(f'''At\n{At} \nBt\n{Bt} \nCt\n{Ct}''')

print('=======================')
#PENJUMLAHAN MATRIKS
print('PENJUMLAHAN MATRIKS')
print(f'A + B\n{A+B} \nA + B\n{A+C} \nB + C\n{B + C}')

print('=======================')
#PENGURANGAN MATRIKS
print('PENGURANGAN MATRIKS')
print(f'A - B\n{A-B} \nA - B\n{A-C} \nB - C\n{B-C}')

print('=======================')
#PERKALIAN MATRIKS
print('PERKALIAN MATRIKS')
AB = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        for k in range(4):
            AB[i][j] += A[i][k] * B[k][j]
AC = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        for k in range(4):
            AC[i][j] += A[i][k] * C[k][j]
BC = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        for k in range(4):
            BC[i][j] += B[i][k] * C[k][j]

print(f'A * B\n{AB} \nA * B\n{AC} \nB * C\n{BC}')

print('=======================')
#PERKALIAN MATRIKS TRANSPOSE
print('PERKALIAN MATRIKS TRANSPOSE')
AAt = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        for k in range(4):
            AAt[i][j] += A[i][k] * At[k][j]
BBt = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        for k in range(4):
            BBt[i][j] += B[i][k] * Bt[k][j]
CCt = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        for k in range(4):
            CCt[i][j] += C[i][k] * Ct[k][j]

print(f'A * At\n{AAt} \nB * Bt\n{BBt} \nC * Ct\n{CCt}')